# AWS
cfn_stack_name: "ocp-test"
region: "us-east-1"
ami: ""
public_hosted_zone: ""
master_instance_type: "t2.large"
infra_instance_type: "t2.large"
app_instance_type: "t2.medium"
bastion_instance_type: "t2.micro"
s3_registry_bucket: "{{ cfn_stack_name }}-registry-{{ availability_zone }}"
s3_registry_user: "{{ cfn_stack_name }}-s3-user"
keypair: "{{ cfn_stack_name }}-keypair"
key_path: "~/.ssh/id_rsa.pub"
vpc_name: "ocp-vpc-{{ cfn_stack_name }}"
vpc_cidr_block: "10.20.0.0/16"
docker_storage: "25"
etcd_storage: "25"
emptydir_storage: "50"

# Single AZ Deployment (Not used if --multi_az flag is set)
availability_zone: "us-east-1a"
private_subnet_cidr: "10.20.1.0/24"
public_subnet_cidr: "10.20.2.0/24"

# Multi AZ Deployment (Only used if --multi_az flag is set)
subnet_cidr_blocks:
  - "10.20.1.0/24"
  - "10.20.2.0/24"
  - "10.20.3.0/24"
  - "10.20.4.0/24"
  - "10.20.5.0/24"
  - "10.20.6.0/24"

# Red Hat Subscription Management
rhsm_user: ""
rhsm_password: ""
rhsm_pool: ""

# OpenShift Cluster
openshift_master_api_port: "443"
openshift_master_cluster_hostname: "ocp-internal.{{ public_hosted_zone }}"
openshift_master_cluster_public_hostname: "ocp.{{ public_hosted_zone }}"
openshift_master_default_subdomain: "apps"
