---
- name: Add bastion to group
  add_host:
    name: "bastion.{{ public_hosted_zone }}"
    groups: bastion

- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: masters, etcd, nodes, cluster_hosts
    openshift_node_labels:
      role: master
      KubernetesCluster: "{{ cfn_stack_name }}"
  with_items: "{{ groups['tag_openshift_role_master'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == cfn_stack_name

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: infra
      KubernetesCluster: "{{ cfn_stack_name }}"
  with_items: "{{ groups['tag_openshift_role_infra'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == cfn_stack_name

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: app
      KubernetesCluster: "{{ cfn_stack_name }}"
  with_items: "{{ groups['tag_openshift_role_app'] }}"
  when:
    - hostvars[item]['ec2_tag_KubernetesCluster'] == cfn_stack_name

# This is used to only run node setup on new nodes
- name: Add new node instance to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: new_node
  with_items: "{{ next_ec2_name }}.{{ public_hosted_zone }}"