# AWS
cfn_stack_name: 'ocp-test'
region: 'us-east-1'
availability_zone: 'us-east-1a'
ami:
public_hosted_zone:
master_instance_type: 't2.large'
infra_instance_type: 't2.large'
app_instance_type: 't2.medium'
bastion_instance_type: 't2.micro'
s3_registry_bucket: 'ocp-test-registry-us-east-1'
s3_registry_user: 'ocp-test-s3-user'
keypair: 'ocp-test-keypair'
key_path: '~/.ssh/id_pub'

# Red Hat Subscription Management
rhsm_user:
rhsm_password:
rhsm_pool:

