---
- name: Create Greenfield Infrastructure
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ region }}"
    template: "roles/create-cloudformation-stack/files/greenfield.json"
    template_parameters:
      AvailabilityZone: "{{ availability_zone }}"
      Route53HostedZone: "{{ public_hosted_zone }}."
      PublicHostedZone: "{{ public_hosted_zone }}"
      MasterApiPort: "{{ console_port }}"
      MasterHealthTarget: "TCP:{{ console_port }}"
      MasterClusterHostname: "{{ openshift_master_cluster_hostname }}"
      MasterClusterPublicHostname: "{{ openshift_master_cluster_public_hostname }}"
      AppWildcardDomain: "*.{{ wildcard_zone }}"
      VpcCidrBlock: "{{ cidr_block }}"
      VpcName: "{{ vpc_prefix }}"
      SubnetCidrBlocks: "{{ subnet_blocks }}"
      KeyName: "{{ keypair }}"
      MasterInstanceType: "{{ master_instance_type }}"
      AmiId: "{{ ami }}"
      BastionInstanceType: "{{ bastion_instance_type }}"
      BastionUserData: "{{ lookup('file', 'user_data_bastion.yml') | b64encode }}"
      MasterRootVolSize: "10"
      BastionRootVolType: gp2
      MasterRootVolType: gp2
      MasterDockerVolSize: "{{ docker_storage }}"
      MasterDockerVolType: gp2
      MasterEtcdVolSize: "{{ etcd_storage }}"
      MasterEtcdVolType: gp2
      MasterEmptyVolSize: "5"
      MasterEmptyVolType: gp2
      MasterUserData: "{{ lookup('file', 'user_data_master.yml') | b64encode }}"
      InfraInstanceType: "{{ node_instance_type }}"
      InfraRootVolSize: "15"
      InfraRootVolType: gp2
      InfraDockerVolSize: "{{ docker_storage }}"
      InfraDockerVolType: gp2
      NodeEmptyVolSize: "{{ emptydir_storage }}"
      NodeEmptyVolType: gp2
      NodeUserData: "{{ lookup('file', 'user_data_node.yml') | b64encode }}"
      AppNodeInstanceType: "{{ app_instance_type }}"
      NodeRootVolSize: "15"
      NodeRootVolType: gp2
      NodeDockerVolSize: "{{ docker_storage }}"
      NodeDockerVolType: gp2
      S3BucketName: "{{ s3_bucket_name }}"
      S3User: "{{ s3_username }}"
    tags:
      KubernetesCluster: "{{ stack_name }}"
  when: create_vpc == "yes"

- name: Add App Node
  cloudformation:
    stack_name: "{{ stack_name }}-{{ shortname }}"
    state: "present"
    region: "{{ region }}"
    template: "roles/create-cloudformation-stack/files/add-node.json"
    template_parameters:
      NodeName: "{{ fqdn }}"
      NodeSg: "{{ stack['ansible_facts']['cloudformation'][stack_name]['stack_outputs']['NodeSGId'] | default(node_sg) }}"
      Subnet: "{{ subnet_id }}"
      Route53HostedZone: "{{ public_hosted_zone }}."
      KeyName: "{{ keypair }}"
      AmiId: "{{ ami }}"
      InstanceType: "{{ node_instance_type }}"
      NodeEmptyVolSize: "{{ emptydir_storage }}"
      NodeEmptyVolType: gp2
      NodeUserData: "{{ lookup('file', 'user_data_node.yml') | b64encode }}"
      NodeRootVolSize: "15"
      NodeRootVolType: gp2
      NodeDockerVolSize: "{{ docker_storage }}"
      NodeDockerVolType: gp2
      NodeInstanceProfile: "{{ stack['ansible_facts']['cloudformation'][stack_name]['stack_outputs']['NodeARN'] | default(iam_role) }}"
      NodeType: "{{ node_type }}"
    tags:
      KubernetesCluster: "{{ stack_name }}"
  when: create_vpc == "no" and add_node == "yes" and node_type == "app"

- name: Add Infra Node
  cloudformation:
    stack_name: "{{ stack_name }}-{{ shortname }}"
    state: "present"
    region: "{{ region }}"
    template: "roles/create-cloudformation-stack/files/add-infra-node.json"
    template_parameters:
      NodeName: "{{ fqdn }}"
      NodeSg: "{{ stack['ansible_facts']['cloudformation'][stack_name]['stack_outputs']['NodeSGId'] | default(node_sg) }}"
      InfraSg: "{{ stack['ansible_facts']['cloudformation'][stack_name]['stack_outputs']['InfraSGId'] | default(infra_sg) }}"
      Subnet: "{{ subnet_id }}"
      Route53HostedZone: "{{ public_hosted_zone }}."
      KeyName: "{{ keypair }}"
      AmiId: "{{ ami }}"
      InstanceType: "{{ node_instance_type }}"
      NodeEmptyVolSize: "{{ emptydir_storage }}"
      NodeEmptyVolType: gp2
      NodeUserData: "{{ lookup('file', 'user_data_node.yml') | b64encode }}"
      NodeRootVolSize: "15"
      NodeRootVolType: gp2
      NodeDockerVolSize: "{{ docker_storage }}"
      NodeDockerVolType: gp2
      NodeInstanceProfile: "{{ stack['ansible_facts']['cloudformation'][stack_name]['stack_outputs']['NodeARN'] | default(iam_role) }}"
      NodeType: "{{ node_type }}"
    tags:
      KubernetesCluster: "{{ stack_name }}"
  when: create_vpc == "no" and add_node == "yes" and node_type == "infra"
