---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - get-cfn-stack-outputs
  - add-infra-to-host-groups

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - wait-for-bastion

- include: aws-prerequisite.yaml

- include: openshift-setup.yaml
